name: DEPLOY BACKEND

on: 
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t thashree11/book-store-backend .

      - name: Publish Image to DockerHub
        run: docker push thashree11/book-store-backend:latest
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from DockerHub
        run: sudo docker pull thashree11/book-store-backend:latest

      - name: Delete Container
        run: sudo docker rm -f backend-container

      - name: Run Docker Container
        run: sudo docker run -d -p 5555:5555 --name backend-container thashree11/book-store-backend:latest
