name : DEPLOY BACKEND

on : 
  push:
    branches:
      - main

jobs:

  build:
   runs-on: ubuntu-latest
   steps:
    -name: Checkout Source
    uses: actions/checkout@v4
    -name: Login to Dockerhub
    run:  docker login -u ${{ secrets.DOCKER_USER_NAME}} -p ${{ secrets.DOCKER_PASSWORD}}
